# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gZxYCa86aIDHmB8rt6pTswTnTHV5JGy
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile euler_solver.py
# 
# import numpy as np
# 
# def euler(f, y0, t):
#     y = np.zeros((len(t), len(y0)))
#     y[0] = y0
#     dt = t[1] - t[0]
# 
#     for i in range(len(t) - 1):
#         y[i+1] = y[i] + dt * f(t[i], y[i])
# 
#     return y
#